import type { Metadata } from 'next'
import localFont from 'next/font/local'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { ThemeProvider } from '@/components/providers/theme-provider'

// Load local fonts
const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})

const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

// Metadata for the document
export const metadata: Metadata = {
	title: 'Eorim чатик',
	description: 'Generated by create next app',
}

// Root layout component
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider>
			<html lang='en' suppressHydrationWarning>
				<ThemeProvider
					attribute='class'
					defaultTheme='dark'
					enableSystem={false}
					storageKey='eorim-theme'
				>
					<body className={`${geistSans.variable} ${geistMono.variable} dark`}>
						{children}
					</body>
				</ThemeProvider>
			</html>
		</ClerkProvider>
	)
}
